name: Innovation Sheet Updater

on:
  workflow_dispatch:

  schedule:
    # 11:30 AM IST (06:00 UTC)
    - cron: "0 6 * * *"
    # 4:30 PM IST (11:00 UTC)
    - cron: "0 11 * * *"

jobs:
  run-updater:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      EXPRESSO_USERNAME: ${{ secrets.EXPRESSO_USERNAME }}
      EXPRESSO_PASSWORD: ${{ secrets.EXPRESSO_PASSWORD }}
      GOOGLE_SHEET_URL: ${{ secrets.GOOGLE_SHEET_URL }}
      SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      DISPLAY: :99.0

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install system dependencies & Chrome
        run: |
          umask 000
          export GIT_LFS_SKIP_SMUDGE=1

          sudo apt-get update
          sudo apt-get install -y wget gnupg2 curl tree xvfb \
            libnss3 libxss1 libasound2 || true

          # Install Google Chrome
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub \
            | gpg --dearmor \
            | sudo tee /usr/share/keyrings/google-chrome.gpg > /dev/null

          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] \
            http://dl.google.com/linux/chrome/deb/ stable main" \
            | sudo tee /etc/apt/sources.list.d/google-chrome.list

          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

          google-chrome --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          python -c "import selenium, openpyxl, gspread, google.auth; print('✅ Dependencies OK')"

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &

      - name: Setup directories and service account
        run: |
          echo "=== Setting up directories ==="
          rm -rf /tmp/BookingData_folder
          mkdir -p /tmp/BookingData_folder logs
          chmod -R 777 /tmp/BookingData_folder logs
          touch logs/download.log logs/processing.log logs/error.log
          chmod 666 logs/*.log

          echo "=== Creating service account file ==="
          echo "$SERVICE_ACCOUNT_JSON" | base64 -d > /tmp/service-account.json
          chmod 600 /tmp/service-account.json

          if [ ! -s "/tmp/service-account.json" ]; then
            echo "❌ Service account JSON missing or empty"
            exit 1
          fi

      - name: Run main.py (Download step)
        run: |
          export CHROME_BIN=/usr/bin/google-chrome
          python -u main.py 2>&1 | tee logs/download.log

      - name: Verify BookingData.xlsx
        run: |
          max_wait_attempts=30
          attempt=1
          file_ready=0

          while [ $attempt -le $max_wait_attempts ]; do
            echo "Attempt $attempt: Checking BookingData.xlsx"
            if [ -f "/tmp/BookingData_folder/BookingData.xlsx" ]; then
              size1=$(stat -c%s "/tmp/BookingData_folder/BookingData.xlsx")
              sleep 5
              size2=$(stat -c%s "/tmp/BookingData_folder/BookingData.xlsx")
              if [ "$size1" = "$size2" ]; then
                echo "✅ File stable: $size2 bytes"
                file_ready=1
                break
              fi
            fi
            sleep 10
            attempt=$((attempt + 1))
          done

          if [ $file_ready -eq 0 ]; then
            echo "❌ BookingData.xlsx not ready"
            exit 1
          fi

      - name: Run data_processing.py
        run: |
          export SERVICE_ACCOUNT_FILE=/tmp/service-account.json
          python -u data_processing.py 2>&1 | tee logs/processing.log

      - name: Run send_email.py
        run: |
          python -u send_email.py 2>&1 | tee -a logs/processing.log

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: innovation-sheet-artifacts
          path: |
            /tmp/BookingData_folder/**
            logs/**
            error_*.png
